# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_group_controller
    - rotary_table_controller

  arm_group_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default_goal_time: 0.0
    joints:
      - joint_a1
      - joint_a2
      - joint_a3
      - joint_a4
      - joint_a5
      - joint_a6
  rotary_table_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default_goal_time: 0.0
    joints:
    - cylinder_to_drill_bit

