# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      
arm_group_controller:
  ros__parameters:
    joints:
      - joint_a1
      - joint_a2
      - joint_a3
      - joint_a4
      - joint_a5
      - joint_a6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    
    constraints:
      goal_time: 0.0
      stopped_velocity_tolerance: 0.0
      joint_a1:
        goal: 0.05
      joint_a2:
        goal: 0.05
      joint_a3:
        goal: 0.05
      joint_a4:
        goal: 0.05
      joint_a5:
        goal: 0.05
      joint_a6:
        goal: 0.05